---
title: "ts_project"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Topicos Selectos: Questions

### Stack Overflow 2018

1.- Do you contribute to open source projects?

2.- In which country do you currently reside?

3- Are you currently enrolled in a formal, degree-granting college or university program?

4.- Which of the following best describes your current employment status?

5.- Which of the following best describes the highest level of formal education that you’ve completed?

Data [https://insights.stackoverflow.com/survey]

### Data for Software Engineering Teamwork Assessment in Education Setting Data Set 


1.-How many observations per year?

2.- In which year and season the collection data process began?

3.- How many observations the data shows per gender (male vs female) in total. And how many observations per gender (male vs female) is divided by year?

4.- How many students are grouped by each team? And how many students are grouped by each team per semester and per year? (This question should show 3 graphs)

5.- What is the relationship between the number of commits (commitCount) and the total hours of coding deliverables (codingDeliveablesHoursTotal)? Can we infer a relationship? Could we define this relationship as positive or negative?

Data [https://archive.ics.uci.edu/ml/datasets/Data+for+Software+Engineering+Teamwork+Assessment+in+Education+Setting]

